name: Generate and upload custom image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  release:
    types: published

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate custom images
    steps:
      - name: Install qemu-img, fdisk and mtools
        run: sudo apt-get update && sudo apt-get install -y qemu-utils fdisk mtools
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Download official image and create custom images
        run: python run_all.py
      - name: Upload autologin + ssh image
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-os-autologin-ssh-img
          path: rpiosimage/*-autologin-ssh.img
          if-no-files-found: error
      - name: Upload autologin + ssh + expanded image
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-os-autologin-ssh-expanded-img
          path: rpiosimage/*-autologin-ssh-expanded.img
          if-no-files-found: error
      - name: Upload Mu image
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-os-mu
          path: rpiosimage/*-mu.img
          if-no-files-found: error

  release-asset:
    name: Upload artifact as GH Release asset
    needs: gen-image
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Set the GH Release tag to env variable $TAG
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download autologin + ssh OS image
        uses: actions/download-artifact@v4
        id: download-zip-autologin-ssh
        with:
          name: raspberry-pi-os-autologin-ssh-img
          path: autologin-ssh
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-autologin-ssh.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh.zip ./*
      - name: Upload autologin + ssh OS image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-autologin-ssh.outputs.download-path}}/raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh.zip
          asset_name: raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh.zip
          asset_content_type: application/zip

      - name: Download autologin + ssh + expanded OS image
        uses: actions/download-artifact@v4
        id: download-zip-autologin-ssh-expanded
        with:
          name: raspberry-pi-os-autologin-ssh-expanded-img
          path: autologin-ssh-expanded
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-autologin-ssh-expanded.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh-expanded.zip ./*
      - name: Upload autologin + ssh OS image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-autologin-ssh-expanded.outputs.download-path}}/raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh-expanded.zip
          asset_name: raspberry-pi-os-lite-${{ env.TAG }}-autologin-ssh-expanded.zip
          asset_content_type: application/zip

      - name: Download Mu image
        uses: actions/download-artifact@v4
        id: download-zip-mu
        with:
          name: raspberry-pi-os-mu
          path: mu
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-mu.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ env.TAG }}-mu.zip ./*
      - name: Upload Mu image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-mu.outputs.download-path}}/raspberry-pi-os-lite-${{ env.TAG }}-mu.zip
          asset_name: raspberry-pi-os-lite-${{ env.TAG }}-mu.zip
          asset_content_type: application/zip
